'use strict';

const variants = {
  a: { title: '案A: 現状維持＋小整理', size: '実装規模: 小', description: 'Always / Resume / tab構成を維持し、見出し・余白・操作結果の説明だけを整える基準案です。', pro: '現行の理解と実装を最も保ちやすい。', con: '操作の影響範囲は読まないと分かりにくいまま残る。' },
  b: { title: '案B: State / Context / Actions の3区分', size: '実装規模: 中', description: '現在状態、保存済みcontext、操作を明確に分離し、操作の読取・更新対象を短く示します。', pro: '現在情報と保存情報、書込み境界を最も予測しやすい。', con: '区分を増やすぶん、見出しがやや増える。' },
  c: { title: '案C: 次の行動を中心にした構成', size: '実装規模: 中', description: '任意操作の自由度を保ったまま、「確認 → 準備 → 保存 → 引継ぎ」の行動を主役にします。', pro: '再開直後に次の一手を選びやすい。', con: '状態の一覧性を重視する利用者には手順寄りに見える。' }
};
const state = { variant: 'a', mode: 'saved' };
const detail = document.querySelector('#detail-pane');
const stateSelect = document.querySelector('#state-select');
function badge(text, tone = '') { return `<span class="badge ${tone}">${text}</span>`; }
function action(name, reads, changes, enabled = true) { return `<button class="action" ${enabled ? '' : 'disabled'}><strong>${name}</strong><span>読む: ${reads}</span><span>変える: ${changes}</span></button>`; }
function currentState() { return `<section class="card current"><div class="card-title"><h3>Current repository state</h3>${badge('live', 'live')}</div><dl class="facts"><div><dt>branch</dt><dd>master</dd></div><div><dt>latest commit</dt><dd>Reorganize mobile project details</dd></div><div><dt>status</dt><dd>${badge('active', 'active')} clean</dd></div><div><dt>next action</dt><dd>Detail pane comparison mockを確認する</dd></div></dl><p class="hint">Rescan projectで git / README / PROGRESS 等を再取得します。保存済みcontextは変更しません。</p></section>`; }
function savedContext(mode) { const has = mode === 'saved'; const draft = mode === 'draft'; return `<section class="card context"><div class="card-title"><h3>Saved work context</h3>${has ? badge('saved', 'saved') : draft ? badge('draft', 'draft') : badge('not saved')}</div>${has ? `<p><strong>Current focus</strong><br>詳細ペインの情報整理を比較し、採用案を決める。</p><p><strong>Command hints</strong><br><code>npm test</code>　<button class="text-button">Copy</button></p>` : draft ? `<p class="draft-box">Auto-fill候補: README / PROGRESS由来の再開情報。まだ保存されていません。</p>` : `<p class="muted">保存済みAgent contextはありません。Auto-fillで候補を作るか、直接入力して保存できます。</p>`}<p class="hint">Save contextでのみ保存されます。Rescanはこの内容を書き換えません。</p></section>`; }
function handoff() { return `<section class="card handoff"><div class="card-title"><h3>AI handoff</h3>${badge('copy only')}</div><p>現在のrepo状態と保存済みcontextを、用途別の引継ぎMarkdownにまとめます。</p>${action('Copy AI Handoff', 'Current state + saved context', 'clipboard only')}</section>`; }
function actions(mode) { const canSave = mode === 'draft' || mode === 'none'; return `<section class="card actions"><div class="card-title"><h3>Actions</h3><span class="muted">操作の影響を短く表示</span></div><div class="action-grid">${action('Rescan project', 'Current repository state', 'Current repository state')}${action('Auto-fill context', 'README / PROGRESS / status', 'フォーム上の候補のみ')}${action('Save context', 'フォーム上のcontext', 'Saved work context', canSave)}${action('Copy AI Handoff', 'Current state + saved context', 'clipboard only')}</div></section>`; }
function renderA() { return `<div class="detail-head"><div><p class="eyebrow">Selected project</p><h2>agent-workbench</h2></div>${badge('active', 'active')}</div><div class="result-line">操作結果: contextは保存済みです。Rescanは現在のrepo状態のみ更新します。</div>${currentState()}${savedContext(state.mode)}<div class="tabs"><button class="active">Documents</button><button>Context</button><button>Diagnostics</button></div>${handoff()}`; }
function renderB() { return `<div class="detail-head"><div><p class="eyebrow">Selected project</p><h2>agent-workbench</h2></div>${badge('active', 'active')}</div><div class="three-zones"><div class="zone-label">1 · STATE <span>現在の観測値</span></div>${currentState()}<div class="zone-label">2 · CONTEXT <span>明示保存した作業文脈</span></div>${savedContext(state.mode)}<div class="zone-label">3 · ACTIONS / HANDOFF <span>何を読む・変えるか</span></div>${actions(state.mode)}</div>`; }
function renderC() { return `<div class="detail-head"><div><p class="eyebrow">Selected project</p><h2>agent-workbench</h2></div>${badge('active', 'active')}</div><section class="next-up"><p class="eyebrow">Next up</p><h3>再開前に、現在状態と保存contextの差を確認する</h3><p>任意の操作を直接選べます。手順の強制はありません。</p></section><div class="flow"><section><span>1</span><div><h3>状態を確認</h3><p>branch / status / next action</p>${currentState()}</div></section><section><span>2</span><div><h3>AI向けcontextを準備</h3><p>Auto-fillは候補をフォームへ入れるだけ</p>${savedContext(state.mode)}</div></section><section><span>3</span><div><h3>保存・引継ぎ</h3><p>Saveは明示保存、Copyはclipboardのみ</p>${actions(state.mode)}</div></section></div>`; }
function render() { document.querySelectorAll('.choice').forEach((button) => button.classList.toggle('active', button.dataset.variant === state.variant)); const info = variants[state.variant]; document.querySelector('#variant-title').textContent = info.title; document.querySelector('#scope').textContent = info.size; document.querySelector('#variant-description').textContent = info.description; document.querySelector('#pro').textContent = info.pro; document.querySelector('#con').textContent = info.con; if (state.mode === 'empty') { detail.innerHTML = document.querySelector('#empty-template').innerHTML; return; } detail.innerHTML = state.variant === 'a' ? renderA() : state.variant === 'b' ? renderB() : renderC(); }
document.querySelectorAll('.choice').forEach((button) => button.addEventListener('click', () => { state.variant = button.dataset.variant; render(); }));
stateSelect.addEventListener('change', () => { state.mode = stateSelect.value; render(); });
render();
